# Generated by Django 5.2.4 on 2025-07-26 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor aluguel')),
                ('valor_iptu', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor IPTU')),
                ('iptu_parcelas', models.PositiveSmallIntegerField(default=10, verbose_name='IPTU parcelas')),
                ('data_inicio', models.DateField(verbose_name='Início do contrato')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Término do contrato')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imovel', verbose_name='Imóvel')),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.locatario', verbose_name='Locatário')),
            ],
        ),
        migrations.CreateModel(
            name='Taxa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da taxa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor da taxa')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxas', to='core.contrato')),
            ],
        ),
    ]
